// Auto-generated by .github/workflows/rotate-token.yml
// Do not edit manually — this file is overwritten every rotation.
module.exports = {
  AUTH_HEADER_VALUE: 'Y2FyZWVyLmhlbHBkZXNrQGRqdHJ1c3Qub3JnOiI1NjU4YzFlZC1iODlmLTQyMTctOTI0ZC1jZGNlNzAzNGVkMTYi',
};
