// Auto-generated by .github/workflows/rotate-token.yml
// Do not edit manually — this file is overwritten every rotation.
module.exports = {
  AUTH_HEADER_VALUE: 'Y2FyZWVyLmhlbHBkZXNrQGRqdHJ1c3Qub3JnOmQ2YTU3MGY3LTFlMTYtNDNhOC1iYTk4LWFlNThhYmU3NjJjNA==',
};
